#!/bin/bash
set -eu

SERVICES=(pvedaemon pve-ha-lrm pve-ha-crm)

case "$1" in
    configure)
        systemctl daemon-reload >/dev/null 2>&1 || true

	for service in ${SERVICES[@]}; do
		if systemctl is-active --quiet "$service"; then
		    systemctl restart "$service" >/dev/null 2>&1 || true
		fi
	done
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
